export const COUNTRIES: Record<string, { name: string; currency: string; symbol: string; flag: string; locale: string }> = {
  AF: { name: 'Afghanistan', currency: 'AFN', symbol: '؋', flag: '🇦🇫', locale: 'ps-AF' },
  AL: { name: 'Albania', currency: 'ALL', symbol: 'L', flag: '🇦🇱', locale: 'sq-AL' },
  DZ: { name: 'Algeria', currency: 'DZD', symbol: 'د.ج', flag: '🇩🇿', locale: 'ar-DZ' },
  AD: { name: 'Andorra', currency: 'EUR', symbol: '€', flag: '🇦🇩', locale: 'ca-AD' },
  AO: { name: 'Angola', currency: 'AOA', symbol: 'Kz', flag: '🇦🇴', locale: 'pt-AO' },
  AG: { name: 'Antigua and Barbuda', currency: 'XCD', symbol: '$', flag: '🇦🇬', locale: 'en-AG' },
  AR: { name: 'Argentina', currency: 'ARS', symbol: '$', flag: '🇦🇷', locale: 'es-AR' },
  AM: { name: 'Armenia', currency: 'AMD', symbol: '֏', flag: '🇦🇲', locale: 'hy-AM' },
  AU: { name: 'Australia', currency: 'AUD', symbol: '$', flag: '🇦🇺', locale: 'en-AU' },
  AT: { name: 'Austria', currency: 'EUR', symbol: '€', flag: '🇦🇹', locale: 'de-AT' },
  AZ: { name: 'Azerbaijan', currency: 'AZN', symbol: '₼', flag: '🇦🇿', locale: 'az-AZ' },
  BS: { name: 'Bahamas', currency: 'BSD', symbol: '$', flag: '🇧🇸', locale: 'en-BS' },
  BH: { name: 'Bahrain', currency: 'BHD', symbol: '.د.ب', flag: '🇧🇭', locale: 'ar-BH' },
  BD: { name: 'Bangladesh', currency: 'BDT', symbol: '৳', flag: '🇧🇩', locale: 'bn-BD' },
  BB: { name: 'Barbados', currency: 'BBD', symbol: '$', flag: '🇧🇧', locale: 'en-BB' },
  BY: { name: 'Belarus', currency: 'BYN', symbol: 'Br', flag: '🇧🇾', locale: 'be-BY' },
  BE: { name: 'Belgium', currency: 'EUR', symbol: '€', flag: '🇧🇪', locale: 'nl-BE' },
  BZ: { name: 'Belize', currency: 'BZD', symbol: '$', flag: '🇧🇿', locale: 'en-BZ' },
  BJ: { name: 'Benin', currency: 'XOF', symbol: 'CFA', flag: '🇧🇯', locale: 'fr-BJ' },
  BT: { name: 'Bhutan', currency: 'BTN', symbol: 'Nu.', flag: '🇧🇹', locale: 'dz-BT' },
  BO: { name: 'Bolivia', currency: 'BOB', symbol: 'Bs.', flag: '🇧🇴', locale: 'es-BO' },
  BA: { name: 'Bosnia and Herzegovina', currency: 'BAM', symbol: 'KM', flag: '🇧🇦', locale: 'bs-BA' },
  BW: { name: 'Botswana', currency: 'BWP', symbol: 'P', flag: '🇧🇼', locale: 'en-BW' },
  BR: { name: 'Brazil', currency: 'BRL', symbol: 'R$', flag: '🇧🇷', locale: 'pt-BR' },
  BN: { name: 'Brunei', currency: 'BND', symbol: '$', flag: '🇧🇳', locale: 'ms-BN' },
  BG: { name: 'Bulgaria', currency: 'BGN', symbol: 'лв', flag: '🇧🇬', locale: 'bg-BG' },
  BF: { name: 'Burkina Faso', currency: 'XOF', symbol: 'CFA', flag: '🇧🇫', locale: 'fr-BF' },
  BI: { name: 'Burundi', currency: 'BIF', symbol: 'FBu', flag: '🇧🇮', locale: 'rn-BI' },
  CV: { name: 'Cabo Verde', currency: 'CVE', symbol: '$', flag: '🇨🇻', locale: 'pt-CV' },
  KH: { name: 'Cambodia', currency: 'KHR', symbol: '៛', flag: '🇰🇭', locale: 'km-KH' },
  CM: { name: 'Cameroon', currency: 'XAF', symbol: 'FCFA', flag: '🇨🇲', locale: 'fr-CM' },
  CA: { name: 'Canada', currency: 'CAD', symbol: '$', flag: '🇨🇦', locale: 'en-CA' },
  CF: { name: 'Central African Republic', currency: 'XAF', symbol: 'FCFA', flag: '🇨🇫', locale: 'fr-CF' },
  TD: { name: 'Chad', currency: 'XAF', symbol: 'FCFA', flag: '🇹🇩', locale: 'fr-TD' },
  CL: { name: 'Chile', currency: 'CLP', symbol: '$', flag: '🇨🇱', locale: 'es-CL' },
  CN: { name: 'China', currency: 'CNY', symbol: '¥', flag: '🇨🇳', locale: 'zh-CN' },
  CO: { name: 'Colombia', currency: 'COP', symbol: '$', flag: '🇨🇴', locale: 'es-CO' },
  KM: { name: 'Comoros', currency: 'KMF', symbol: 'CF', flag: '🇰🇲', locale: 'fr-KM' },
  CD: { name: 'Congo (DRC)', currency: 'CDF', symbol: 'FC', flag: '🇨🇩', locale: 'fr-CD' },
  CG: { name: 'Congo (Republic)', currency: 'XAF', symbol: 'FCFA', flag: '🇨🇬', locale: 'fr-CG' },
  CR: { name: 'Costa Rica', currency: 'CRC', symbol: '₡', flag: '🇨🇷', locale: 'es-CR' },
  HR: { name: 'Croatia', currency: 'EUR', symbol: '€', flag: '🇭🇷', locale: 'hr-HR' },
  CU: { name: 'Cuba', currency: 'CUP', symbol: '$', flag: '🇨🇺', locale: 'es-CU' },
  CY: { name: 'Cyprus', currency: 'EUR', symbol: '€', flag: '🇨🇾', locale: 'el-CY' },
  CZ: { name: 'Czechia', currency: 'CZK', symbol: 'Kč', flag: '🇨🇿', locale: 'cs-CZ' },
  DK: { name: 'Denmark', currency: 'DKK', symbol: 'kr', flag: '🇩🇰', locale: 'da-DK' },
  DJ: { name: 'Djibouti', currency: 'DJF', symbol: 'Fdj', flag: '🇩🇯', locale: 'fr-DJ' },
  DM: { name: 'Dominica', currency: 'XCD', symbol: '$', flag: '🇩🇲', locale: 'en-DM' },
  DO: { name: 'Dominican Republic', currency: 'DOP', symbol: 'RD$', flag: '🇩🇴', locale: 'es-DO' },
  EC: { name: 'Ecuador', currency: 'USD', symbol: '$', flag: '🇪🇨', locale: 'es-EC' },
  EG: { name: 'Egypt', currency: 'EGP', symbol: '£', flag: '🇪🇬', locale: 'ar-EG' },
  SV: { name: 'El Salvador', currency: 'USD', symbol: '$', flag: '🇸🇻', locale: 'es-SV' },
  GQ: { name: 'Equatorial Guinea', currency: 'XAF', symbol: 'FCFA', flag: '🇬🇶', locale: 'es-GQ' },
  ER: { name: 'Eritrea', currency: 'ERN', symbol: 'Nfk', flag: '🇪🇷', locale: 'ti-ER' },
  EE: { name: 'Estonia', currency: 'EUR', symbol: '€', flag: '🇪🇪', locale: 'et-EE' },
  SZ: { name: 'Eswatini', currency: 'SZL', symbol: 'L', flag: '🇸🇿', locale: 'en-SZ' },
  ET: { name: 'Ethiopia', currency: 'ETB', symbol: 'Br', flag: '🇪🇹', locale: 'am-ET' },
  FJ: { name: 'Fiji', currency: 'FJD', symbol: '$', flag: '🇫🇯', locale: 'en-FJ' },
  FI: { name: 'Finland', currency: 'EUR', symbol: '€', flag: '🇫🇮', locale: 'fi-FI' },
  FR: { name: 'France', currency: 'EUR', symbol: '€', flag: '🇫🇷', locale: 'fr-FR' },
  GA: { name: 'Gabon', currency: 'XAF', symbol: 'FCFA', flag: '🇬🇦', locale: 'fr-GA' },
  GM: { name: 'Gambia', currency: 'GMD', symbol: 'D', flag: '🇬🇲', locale: 'en-GM' },
  GE: { name: 'Georgia', currency: 'GEL', symbol: '₾', flag: '🇬🇪', locale: 'ka-GE' },
  DE: { name: 'Germany', currency: 'EUR', symbol: '€', flag: '🇩🇪', locale: 'de-DE' },
  GH: { name: 'Ghana', currency: 'GHS', symbol: '₵', flag: '🇬🇭', locale: 'en-GH' },
  GR: { name: 'Greece', currency: 'EUR', symbol: '€', flag: '🇬🇷', locale: 'el-GR' },
  GD: { name: 'Grenada', currency: 'XCD', symbol: '$', flag: '🇬🇩', locale: 'en-GD' },
  GT: { name: 'Guatemala', currency: 'GTQ', symbol: 'Q', flag: '🇬🇹', locale: 'es-GT' },
  GN: { name: 'Guinea', currency: 'GNF', symbol: 'FG', flag: '🇬🇳', locale: 'fr-GN' },
  GW: { name: 'Guinea-Bissau', currency: 'XOF', symbol: 'CFA', flag: '🇬🇼', locale: 'pt-GW' },
  GY: { name: 'Guyana', currency: 'GYD', symbol: '$', flag: '🇬🇾', locale: 'en-GY' },
  HT: { name: 'Haiti', currency: 'HTG', symbol: 'G', flag: '🇭🇹', locale: 'fr-HT' },
  HN: { name: 'Honduras', currency: 'HNL', symbol: 'L', flag: '🇭🇳', locale: 'es-HN' },
  HU: { name: 'Hungary', currency: 'HUF', symbol: 'Ft', flag: '🇭🇺', locale: 'hu-HU' },
  IS: { name: 'Iceland', currency: 'ISK', symbol: 'kr', flag: '🇮🇸', locale: 'is-IS' },
  IN: { name: 'India', currency: 'INR', symbol: '₹', flag: '🇮🇳', locale: 'en-IN' },
  ID: { name: 'Indonesia', currency: 'IDR', symbol: 'Rp', flag: '🇮🇩', locale: 'id-ID' },
  IR: { name: 'Iran', currency: 'IRR', symbol: '﷼', flag: '🇮🇷', locale: 'fa-IR' },
  IQ: { name: 'Iraq', currency: 'IQD', symbol: 'ع.d', flag: '🇮🇶', locale: 'ar-IQ' },
  IE: { name: 'Ireland', currency: 'EUR', symbol: '€', flag: '🇮🇪', locale: 'en-IE' },
  IL: { name: 'Israel', currency: 'ILS', symbol: '₪', flag: '🇮🇱', locale: 'he-IL' },
  IT: { name: 'Italy', currency: 'EUR', symbol: '€', flag: '🇮🇹', locale: 'it-IT' },
  JM: { name: 'Jamaica', currency: 'JMD', symbol: '$', flag: '🇯🇲', locale: 'en-JM' },
  JP: { name: 'Japan', currency: 'JPY', symbol: '¥', flag: '🇯🇵', locale: 'ja-JP' },
  JO: { name: 'Jordan', currency: 'JOD', symbol: 'د.ا', flag: '🇯🇴', locale: 'ar-JO' },
  KZ: { name: 'Kazakhstan', currency: 'KZT', symbol: '₸', flag: '🇰🇿', locale: 'kk-KZ' },
  KE: { name: 'Kenya', currency: 'KES', symbol: 'KSh', flag: '🇰🇪', locale: 'en-KE' },
  KI: { name: 'Kiribati', currency: 'AUD', symbol: '$', flag: '🇰🇮', locale: 'en-KI' },
  KP: { name: 'Korea (North)', currency: 'KPW', symbol: '₩', flag: '🇰🇵', locale: 'ko-KP' },
  KR: { name: 'Korea (South)', currency: 'KRW', symbol: '₩', flag: '🇰🇷', locale: 'ko-KR' },
  KW: { name: 'Kuwait', currency: 'KWD', symbol: 'د.ك', flag: '🇰🇼', locale: 'ar-KW' },
  KG: { name: 'Kyrgyzstan', currency: 'KGS', symbol: 'с', flag: '🇰🇬', locale: 'ky-KG' },
  LA: { name: 'Laos', currency: 'LAK', symbol: '₭', flag: '🇱🇦', locale: 'lo-LA' },
  LV: { name: 'Latvia', currency: 'EUR', symbol: '€', flag: '🇱🇻', locale: 'lv-LV' },
  LB: { name: 'Lebanon', currency: 'LBP', symbol: 'ل.ل', flag: '🇱🇧', locale: 'ar-LB' },
  LS: { name: 'Lesotho', currency: 'LSL', symbol: 'L', flag: '🇱🇸', locale: 'en-LS' },
  LR: { name: 'Liberia', currency: 'LRD', symbol: '$', flag: '🇱🇷', locale: 'en-LR' },
  LY: { name: 'Libya', currency: 'LYD', symbol: 'ل.d', flag: '🇱🇾', locale: 'ar-LY' },
  LI: { name: 'Liechtenstein', currency: 'CHF', symbol: 'Fr', flag: '🇱🇮', locale: 'de-LI' },
  LT: { name: 'Lithuania', currency: 'EUR', symbol: '€', flag: '🇱🇹', locale: 'lt-LT' },
  LU: { name: 'Luxembourg', currency: 'EUR', symbol: '€', flag: '🇱🇺', locale: 'fr-LU' },
  MG: { name: 'Madagascar', currency: 'MGA', symbol: 'Ar', flag: '🇲🇬', locale: 'mg-MG' },
  MW: { name: 'Malawi', currency: 'MWK', symbol: 'MK', flag: '🇲🇼', locale: 'en-MW' },
  MY: { name: 'Malaysia', currency: 'MYR', symbol: 'RM', flag: '🇲🇾', locale: 'ms-MY' },
  MV: { name: 'Maldives', currency: 'MVR', symbol: 'Rf', flag: '🇲🇻', locale: 'dv-MV' },
  ML: { name: 'Mali', currency: 'XOF', symbol: 'CFA', flag: '🇲🇱', locale: 'fr-ML' },
  MT: { name: 'Malta', currency: 'EUR', symbol: '€', flag: '🇲🇹', locale: 'mt-MT' },
  MH: { name: 'Marshall Islands', currency: 'USD', symbol: '$', flag: '🇲🇭', locale: 'en-MH' },
  MR: { name: 'Mauritania', currency: 'MRU', symbol: 'UM', flag: '🇲🇷', locale: 'ar-MR' },
  MU: { name: 'Mauritius', currency: 'MUR', symbol: '₨', flag: '🇲🇺', locale: 'en-MU' },
  MX: { name: 'Mexico', currency: 'MXN', symbol: '$', flag: '🇲🇽', locale: 'es-MX' },
  FM: { name: 'Micronesia', currency: 'USD', symbol: '$', flag: '🇫🇲', locale: 'en-FM' },
  MD: { name: 'Moldova', currency: 'MDL', symbol: 'L', flag: '🇲🇩', locale: 'ro-MD' },
  MC: { name: 'Monaco', currency: 'EUR', symbol: '€', flag: '🇲🇨', locale: 'fr-MC' },
  MN: { name: 'Mongolia', currency: 'MNT', symbol: '₮', flag: '🇲🇳', locale: 'mn-MN' },
  ME: { name: 'Montenegro', currency: 'EUR', symbol: '€', flag: '🇲🇪', locale: 'sr-ME' },
  MA: { name: 'Morocco', currency: 'MAD', symbol: 'د.م.', flag: '🇲🇦', locale: 'ar-MA' },
  MZ: { name: 'Mozambique', currency: 'MZN', symbol: 'MT', flag: '🇲🇿', locale: 'pt-MZ' },
  MM: { name: 'Myanmar', currency: 'MMK', symbol: 'Ks', flag: '🇲🇲', locale: 'my-MM' },
  NA: { name: 'Namibia', currency: 'NAD', symbol: '$', flag: '🇳🇦', locale: 'en-NA' },
  NR: { name: 'Nauru', currency: 'AUD', symbol: '$', flag: '🇳🇷', locale: 'en-NR' },
  NP: { name: 'Nepal', currency: 'NPR', symbol: '₨', flag: '🇳🇵', locale: 'ne-NP' },
  NL: { name: 'Netherlands', currency: 'EUR', symbol: '€', flag: '🇳🇱', locale: 'nl-NL' },
  NZ: { name: 'New Zealand', currency: 'NZD', symbol: '$', flag: '🇳🇿', locale: 'en-NZ' },
  NI: { name: 'Nicaragua', currency: 'NIO', symbol: 'C$', flag: '🇳🇮', locale: 'es-NI' },
  NE: { name: 'Niger', currency: 'XOF', symbol: 'CFA', flag: '🇳🇪', locale: 'fr-NE' },
  NG: { name: 'Nigeria', currency: 'NGN', symbol: '₦', flag: '🇳🇬', locale: 'en-NG' },
  MK: { name: 'North Macedonia', currency: 'MKD', symbol: 'ден', flag: '🇲🇰', locale: 'mk-MK' },
  NO: { name: 'Norway', currency: 'NOK', symbol: 'kr', flag: '🇳🇴', locale: 'no-NO' },
  OM: { name: 'Oman', currency: 'OMR', symbol: 'ر.ع.', flag: '🇴🇲', locale: 'ar-OM' },
  PK: { name: 'Pakistan', currency: 'PKR', symbol: '₨', flag: '🇵🇰', locale: 'ur-PK' },
  PW: { name: 'Palau', currency: 'USD', symbol: '$', flag: '🇵🇼', locale: 'en-PW' },
  PA: { name: 'Panama', currency: 'PAB', symbol: 'B/.', flag: '🇵🇦', locale: 'es-PA' },
  PG: { name: 'Papua New Guinea', currency: 'PGK', symbol: 'K', flag: '🇵🇬', locale: 'en-PG' },
  PY: { name: 'Paraguay', currency: 'PYG', symbol: '₲', flag: '🇵🇾', locale: 'es-PY' },
  PE: { name: 'Peru', currency: 'PEN', symbol: 'S/.', flag: '🇵🇪', locale: 'es-PE' },
  PH: { name: 'Philippines', currency: 'PHP', symbol: '₱', flag: '🇵🇭', locale: 'en-PH' },
  PL: { name: 'Poland', currency: 'PLN', symbol: 'zł', flag: '🇵🇱', locale: 'pl-PL' },
  PT: { name: 'Portugal', currency: 'EUR', symbol: '€', flag: '🇵🇹', locale: 'pt-PT' },
  QA: { name: 'Qatar', currency: 'QAR', symbol: 'ر.ق', flag: '🇶🇦', locale: 'ar-QA' },
  RO: { name: 'Romania', currency: 'RON', symbol: 'lei', flag: '🇷🇴', locale: 'ro-RO' },
  RU: { name: 'Russia', currency: 'RUB', symbol: '₽', flag: '🇷🇺', locale: 'ru-RU' },
  RW: { name: 'Rwanda', currency: 'RWF', symbol: 'FRw', flag: '🇷🇼', locale: 'rw-RW' },
  KN: { name: 'Saint Kitts and Nevis', currency: 'XCD', symbol: '$', flag: '🇰🇳', locale: 'en-KN' },
  LC: { name: 'Saint Lucia', currency: 'XCD', symbol: '$', flag: '🇱🇨', locale: 'en-LC' },
  VC: { name: 'Saint Vincent and the Grenadines', currency: 'XCD', symbol: '$', flag: '🇻🇨', locale: 'en-VC' },
  WS: { name: 'Samoa', currency: 'WST', symbol: 'T', flag: '🇼🇸', locale: 'en-WS' },
  SM: { name: 'San Marino', currency: 'EUR', symbol: '€', flag: '🇸🇲', locale: 'it-SM' },
  ST: { name: 'Sao Tome and Principe', currency: 'STN', symbol: 'Db', flag: '🇸🇹', locale: 'pt-ST' },
  SA: { name: 'Saudi Arabia', currency: 'SAR', symbol: 'ر.س', flag: '🇸🇦', locale: 'ar-SA' },
  SN: { name: 'Senegal', currency: 'XOF', symbol: 'CFA', flag: '🇸🇳', locale: 'fr-SN' },
  RS: { name: 'Serbia', currency: 'RSD', symbol: 'дин', flag: '🇷🇸', locale: 'sr-RS' },
  SC: { name: 'Seychelles', currency: 'SCR', symbol: '₨', flag: '🇸🇨', locale: 'en-SC' },
  SL: { name: 'Sierra Leone', currency: 'SLE', symbol: 'Le', flag: '🇸🇱', locale: 'en-SL' },
  SG: { name: 'Singapore', currency: 'SGD', symbol: '$', flag: '🇸🇬', locale: 'en-SG' },
  SK: { name: 'Slovakia', currency: 'EUR', symbol: '€', flag: '🇸🇰', locale: 'sk-SK' },
  SI: { name: 'Slovenia', currency: 'EUR', symbol: '€', flag: '🇸🇮', locale: 'sl-SI' },
  SB: { name: 'Solomon Islands', currency: 'SBD', symbol: '$', flag: '🇸🇧', locale: 'en-SB' },
  SO: { name: 'Somalia', currency: 'SOS', symbol: 'S', flag: '🇸🇴', locale: 'so-SO' },
  ZA: { name: 'South Africa', currency: 'ZAR', symbol: 'R', flag: '🇿🇦', locale: 'en-ZA' },
  SS: { name: 'South Sudan', currency: 'SSP', symbol: '£', flag: '🇸🇸', locale: 'en-SS' },
  ES: { name: 'Spain', currency: 'EUR', symbol: '€', flag: '🇪🇸', locale: 'es-ES' },
  LK: { name: 'Sri Lanka', currency: 'LKR', symbol: '₨', flag: '🇱🇰', locale: 'si-LK' },
  SD: { name: 'Sudan', currency: 'SDG', symbol: 'ج.س.', flag: '🇸🇩', locale: 'ar-SD' },
  SR: { name: 'Suriname', currency: 'SRD', symbol: '$', flag: '🇸🇷', locale: 'nl-SR' },
  SE: { name: 'Sweden', currency: 'SEK', symbol: 'kr', flag: '🇸🇪', locale: 'sv-SE' },
  CH: { name: 'Switzerland', currency: 'CHF', symbol: 'Fr', flag: '🇨🇭', locale: 'de-CH' },
  SY: { name: 'Syria', currency: 'SYP', symbol: '£', flag: '🇸🇾', locale: 'ar-SY' },
  TW: { name: 'Taiwan', currency: 'TWD', symbol: 'NT$', flag: '🇹🇼', locale: 'zh-TW' },
  TJ: { name: 'Tajikistan', currency: 'TJS', symbol: 'SM', flag: '🇹🇯', locale: 'tg-TJ' },
  TZ: { name: 'Tanzania', currency: 'TZS', symbol: 'Sh', flag: '🇹🇿', locale: 'sw-TZ' },
  TH: { name: 'Thailand', currency: 'THB', symbol: '฿', flag: '🇹🇭', locale: 'th-TH' },
  TL: { name: 'Timor-Leste', currency: 'USD', symbol: '$', flag: '🇹🇱', locale: 'pt-TL' },
  TG: { name: 'Togo', currency: 'XOF', symbol: 'CFA', flag: '🇹🇬', locale: 'fr-TG' },
  TO: { name: 'Tonga', currency: 'TOP', symbol: 'T$', flag: '🇹🇴', locale: 'en-TO' },
  TT: { name: 'Trinidad and Tobago', currency: 'TTD', symbol: '$', flag: '🇹🇹', locale: 'en-TT' },
  TN: { name: 'Tunisia', currency: 'TND', symbol: 'd.t', flag: '🇹🇳', locale: 'ar-TN' },
  TR: { name: 'Turkey', currency: 'TRY', symbol: '₺', flag: '🇹🇷', locale: 'tr-TR' },
  TM: { name: 'Turkmenistan', currency: 'TMT', symbol: 'm', flag: '🇹🇲', locale: 'tk-TM' },
  TV: { name: 'Tuvalu', currency: 'AUD', symbol: '$', flag: '🇹🇻', locale: 'en-TV' },
  UG: { name: 'Uganda', currency: 'UGX', symbol: 'USh', flag: '🇺🇬', locale: 'en-UG' },
  UA: { name: 'Ukraine', currency: 'UAH', symbol: '₴', flag: '🇺🇦', locale: 'uk-UA' },
  AE: { name: 'United Arab Emirates', currency: 'AED', symbol: 'د.إ', flag: '🇦🇪', locale: 'ar-AE' },
  GB: { name: 'United Kingdom', currency: 'GBP', symbol: '£', flag: '🇬🇧', locale: 'en-GB' },
  US: { name: 'United States', currency: 'USD', symbol: '$', flag: '🇺🇸', locale: 'en-US' },
  UY: { name: 'Uruguay', currency: 'UYU', symbol: '$', flag: '🇺🇾', locale: 'es-UY' },
  UZ: { name: 'Uzbekistan', currency: 'UZS', symbol: 'soʻm', flag: '🇺🇿', locale: 'uz-UZ' },
  VU: { name: 'Vanuatu', currency: 'VUV', symbol: 'Vt', flag: '🇻🇺', locale: 'en-VU' },
  VE: { name: 'Venezuela', currency: 'VES', symbol: 'Bs.', flag: '🇻🇪', locale: 'es-VE' },
  VN: { name: 'Vietnam', currency: 'VND', symbol: '₫', flag: '🇻🇳', locale: 'vi-VN' },
  YE: { name: 'Yemen', currency: 'YER', symbol: '﷼', flag: '🇾🇪', locale: 'ar-YE' },
  ZM: { name: 'Zambia', currency: 'ZMW', symbol: 'ZK', flag: '🇿🇲', locale: 'en-ZM' },
  ZW: { name: 'Zimbabwe', currency: 'ZWL', symbol: '$', flag: '🇿🇼', locale: 'en-ZW' }
};
