import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/components/ConvexClientProvider";
import { getToken } from "@/lib/auth-server";
import { HeroUIProvider } from "@heroui/system";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";
import { ScrollArea } from "@/components/ui/scroll-area";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = await getToken();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`w-full h-dvh overflow-hidden ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          enableSystem
        >
          <HeroUIProvider>
            <ConvexClientProvider initialToken={token}>
                <ScrollArea className="w-full h-dvh">
                  {children}
                </ScrollArea>
                <Toaster />
            </ConvexClientProvider>
          </HeroUIProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

