import type { ComponentPropsWithoutRef, ComponentType } from 'react';
import { cn } from '@/lib/utils';
import {
  AddCircle,
  AddSquare,
  AltArrowDown,
  AltArrowRight,
  AltArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowLeftDown,
  ArrowRight,
  ArrowRightDown,
  ArrowRightUp,
  ArrowUp,
  Bag,
  Bag3,
  Bell,
  BellOff,
  Buildings,
  Bus,
  Calculator,
  Calendar,
  CalendarMark,
  Camera,
  Card,
  ChatLine,
  CheckCircle,
  CheckRead,
  CheckSquare,
  ClockCircle,
  CloseSquare,
  CloudDownload,
  Copy,
  Crown,
  Cpu,
  DangerTriangle,
  Diskette,
  Dollar,
  Download,
  FileText,
  Filter,
  Flag,
  Flashlight,
  Global,
  HamburgerMenu,
  HandMoney,
  Heart,
  HeartPulse,
  History,
  Home,
  IPhone,
  InfoCircle,
  Laptop,
  Letter,
  Lightbulb,
  Lock,
  LockKeyhole,
  LockPassword,
  LockUnlocked,
  Magnifer,
  MapPoint,
  MenuDots,
  MinusCircle,
  Monitor,
  Moon,
  Mug,
  Pen,
  Phone,
  PlusMinus,
  QuestionCircle,
  Refresh,
  Sale,
  SafeSquare,
  SendSquare,
  Settings,
  ShieldCheck,
  ShieldKeyhole,
  ShieldUser,
  ShieldWarning,
  Smartphone,
  Star,
  Suitcase,
  TagPrice,
  TransferHorizontal,
  TransferVertical,
  TrashBinMinimalistic,
  User,
  UsersGroupRounded,
  Wallet,
  Widget,
} from '@solar-icons/react-perf/Linear';
import {
  AddCircle as AddCircleBold,
  CheckCircle as CheckCircleBold,
  DangerTriangle as DangerTriangleBold,
  Heart as HeartBold,
  InfoCircle as InfoCircleBold,
  Lock as LockBold,
  MenuDots as MenuDotsBold,
  ShieldCheck as ShieldCheckBold,
  Star as StarBold,
  User as UserBold,
} from '@solar-icons/react-perf/Bold';
import { Eye, EyeClosed, Logout3, Sun } from '@solar-icons/react-perf/Linear';

type SolarIconComponent = ComponentType<
  ComponentPropsWithoutRef<'svg'> & { size?: string | number; color?: string }
>;

export type RiIconProps = Omit<ComponentPropsWithoutRef<'svg'>, 'color'> & {
  className?: string;
  size?: string | number;
  color?: string;
  fallback?: SolarIconComponent;
};

const ICON_MAP: Record<string, SolarIconComponent> = {
  'ri-add-circle-fill': AddCircleBold,
  'ri-add-circle-line': AddCircle,
  'ri-add-line': AddSquare,
  'ri-alert-fill': DangerTriangleBold,
  'ri-alert-line': DangerTriangle,
  'ri-apple-fill': IPhone,
  'ri-arrow-down-fill': ArrowDown,
  'ri-arrow-down-line': ArrowDown,
  'ri-arrow-down-s-line': AltArrowDown,
  'ri-arrow-left-down-line': ArrowLeftDown,
  'ri-arrow-left-line': ArrowLeft,
  'ri-arrow-right-down-line': ArrowRightDown,
  'ri-arrow-right-line': ArrowRight,
  'ri-arrow-right-s-line': AltArrowRight,
  'ri-arrow-right-up-line': ArrowRightUp,
  'ri-arrow-up-down-line': TransferVertical,
  'ri-arrow-up-fill': ArrowUp,
  'ri-arrow-up-line': ArrowUp,
  'ri-bank-card-fill': Card,
  'ri-bank-card-line': Card,
  'ri-bank-line': Buildings,
  'ri-bar-chart-box-line': Widget,
  'ri-bar-chart-line': Widget,
  'ri-bill-line': FileText,
  'ri-bit-coin-line': Dollar,
  'ri-briefcase-line': Suitcase,
  'ri-building-line': Buildings,
  'ri-calculator-line': Calculator,
  'ri-calendar-check-line': CalendarMark,
  'ri-calendar-event-line': Calendar,
  'ri-calendar-line': Calendar,
  'ri-camera-line': Camera,
  'ri-car-line': Bus,
  'ri-chat-1-line': ChatLine,
  'ri-checkbox-circle-fill': CheckCircleBold,
  'ri-checkbox-circle-line': CheckCircle,
  'ri-check-double-line': CheckRead,
  'ri-check-line': CheckSquare,
  'ri-close-line': CloseSquare,
  'ri-coins-line': Dollar,
  'ri-computer-line': Monitor,
  'ri-cpu-fill': Cpu,
  'ri-credit-card-line': Card,
  'ri-customer-service-2-line': Phone,
  'ri-customer-service-line': Phone,
  'ri-dashboard-line': Widget,
  'ri-delete-bin-line': TrashBinMinimalistic,
  'ri-download-cloud-line': CloudDownload,
  'ri-download-line': Download,
  'ri-edit-line': Pen,
  'ri-emotion-unhappy-line': QuestionCircle,
  'ri-equal-line': PlusMinus,
  'ri-error-warning-fill': DangerTriangleBold,
  'ri-error-warning-line': DangerTriangle,
  'ri-exchange-dollar-line': TransferHorizontal,
  'ri-exchange-line': TransferHorizontal,
  'ri-eye-line': Eye,
  'ri-eye-off-line': EyeClosed,
  'ri-file-copy-line': Copy,
  'ri-file-list-3-line': FileText,
  'ri-file-search-line': Magnifer,
  'ri-file-text-line': FileText,
  'ri-filter-3-line': Filter,
  'ri-fingerprint-line': LockKeyhole,
  'ri-flag-line': Flag,
  'ri-flashlight-fill': Flashlight,
  'ri-facebook-fill': UsersGroupRounded,
  'ri-instagram-fill': Camera,
  'ri-linkedin-fill': Suitcase,
  'ri-twitter-fill': ChatLine,
  'ri-global-line': Global,
  'ri-government-line': Buildings,
  'ri-group-line': UsersGroupRounded,
  'ri-hand-coin-line': HandMoney,
  'ri-heart-fill': HeartBold,
  'ri-heart-line': Heart,
  'ri-heart-pulse-line': HeartPulse,
  'ri-history-line': History,
  'ri-home-line': Home,
  'ri-id-card-line': User,
  'ri-image-add-line': AddCircle,
  'ri-information-fill': InfoCircleBold,
  'ri-information-line': InfoCircle,
  'ri-lightbulb-line': Lightbulb,
  'ri-line-chart-line': TransferVertical,
  'ri-loader-4-line': Refresh,
  'ri-lock-fill': LockBold,
  'ri-lock-line': Lock,
  'ri-lock-password-line': LockPassword,
  'ri-lock-unlock-line': LockUnlocked,
  'ri-logout-box-line': Logout3,
  'ri-logout-box-r-line': Logout3,
  'ri-macbook-line': Laptop,
  'ri-mail-check-line': Letter,
  'ri-mail-line': Letter,
  'ri-mail-send-line': SendSquare,
  'ri-map-pin-2-line': MapPoint,
  'ri-map-pin-line': MapPoint,
  'ri-menu-line': HamburgerMenu,
  'ri-money-dollar-circle-line': Dollar,
  'ri-moon-line': Moon,
  'ri-more-2-fill': MenuDotsBold,
  'ri-more-fill': MenuDots,
  'ri-movie-line': Camera,
  'ri-notification-3-line': Bell,
  'ri-notification-line': Bell,
  'ri-notification-off-line': BellOff,
  'ri-pencil-line': Pen,
  'ri-percent-line': Sale,
  'ri-phone-line': Phone,
  'ri-price-tag-3-line': TagPrice,
  'ri-restaurant-line': Mug,
  'ri-rfid-line': Card,
  'ri-safe-line': SafeSquare,
  'ri-save-line': Diskette,
  'ri-search-line': Magnifer,
  'ri-send-plane-fill': SendSquare,
  'ri-settings-3-line': Settings,
  'ri-settings-4-line': Settings,
  'ri-shield-alert-line': ShieldWarning,
  'ri-shield-check-fill': ShieldCheckBold,
  'ri-shield-check-line': ShieldCheck,
  'ri-shield-keyhole-line': ShieldKeyhole,
  'ri-shield-key-line': ShieldKeyhole,
  'ri-shield-user-line': ShieldUser,
  'ri-shopping-bag-3-line': Bag3,
  'ri-shopping-bag-line': Bag,
  'ri-smartphone-line': Smartphone,
  'ri-star-fill': StarBold,
  'ri-star-smile-line': Star,
  'ri-steering-2-line': Bus,
  'ri-subtract-line': MinusCircle,
  'ri-sun-line': Sun,
  'ri-time-line': ClockCircle,
  'ri-translate-2': Global,
  'ri-user-3-fill': UserBold,
  'ri-user-line': User,
  'ri-user-settings-line': User,
  'ri-user-smile-line': User,
  'ri-user-unfollow-line': User,
  'ri-vip-crown-fill': Crown,
  'ri-vip-diamond-fill': Star,
  'ri-visa-line': Card,
  'ri-wallet-3-line': Wallet,
  'ri-wallet-line': Wallet,
  'ri-windows-fill': Monitor,
};

function extractRiClass(className?: string) {
  const tokens = className?.split(/\s+/).filter(Boolean) ?? [];
  const riClass = tokens.find((t) => t.startsWith('ri-'));
  const rest = tokens.filter((t) => t !== riClass).join(' ');
  return { riClass, restClassName: rest };
}

export default function RiIcon({
  className,
  size,
  color,
  fallback = QuestionCircle,
  ...svgProps
}: RiIconProps) {
  const { riClass, restClassName } = extractRiClass(className);
  const ResolvedIcon = (riClass && ICON_MAP[riClass]) || fallback;

  return (
    <ResolvedIcon
      {...svgProps}
      size={size ?? '1em'}
      color={color}
      className={cn(restClassName)}
    />
  );
}
